### PR TITLE
FIX #606, correct URL for categories if Blog is on /home

### LINKED ISSUE #606: BlogObject filter URLs break if the Blog is the homepage
If you set the homepage ('/home' URLSegment) to be a Blog page type, the Link() function on BlogObject that links to the category and tag filters do not work. The links become things like '/category/test' instead of '/home/category/test,' which would work fine. 

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/804

### PR DESCRIPTION
**Pull request by lerni**
## Description
Get correct URL for categories if Blog is on `/home`. For categories `$this->Blog()->Link()` returns just `/` but should return `/home`.
## Manual testing steps
Create a Blog on `/home` and see categories fail
```
[User Warning] Request handler SilverStripe\CMS\Controllers\ModelAsController does not have a url_segment defined. Relying on this link may be an application error
GET /category/...

Line 573 in /var/www/html/vendor/silverstripe/framework/src/Control/RequestHandler.php
```
## Issues
- #606

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

File: src/Model/BlogObject.php [hunk 1]
```diff
@@ -83,7 +83,7 @@ public function validate()
     public function getLink()
     {
         return Controller::join_links(
-            $this->Blog()->Link(),
+            $this->Blog()->Link(true),
             $this->getListUrlSegment(),
             $this->URLSegment
         );
```
Comment (ChloeSartorelli) [inline src/Model/BlogObject.php]: This does work, but it relies on a pretty weak `falsy` check against a parameter that's meant to be `string|null` - passing a boolean isn't really _supposed_ to be done.
Passing the routing portion as the "action" seems like a more reliable way to go.

```suggestion
        return $this->Blog()->Link(Controller::join_links(
            $this->getListUrlSegment(),
            $this->URLSegment
        ));
```

**Review by GuySartorelli — CHANGES_REQUESTED** [review]

**Comment by GuySartorelli** [comment]
Please also target this PR to the `4.3` branch so it can be released as a patch instead of waiting for the next minor release

**Comment by GuySartorelli** [comment]
Please also update the commit message both to reflect the bug that is being fixed and to include the correct commit prefix (there's a link in the PR checklist for commit messages) - and check the checklist while you're at it. That checklist is there to help you as the contributor make sure you've got all these sorts of things correct and it's ready for review.

**Comment by GuySartorelli** [comment]
Finally, if you could add a unit test for this that would be great!

File: src/Model/BlogObject.php (hunk 1 above)
Comment (lerni) [reply src/Model/BlogObject.php]: adapted as requested

**Review by GuySartorelli — APPROVED** [review]
LGTM, works well locally and good unit test.
We don't usually include the issue URL in a PHPDoc but it's not worth delaying merging for that.
Thanks for submitting this!
