### PR TITLE
FIX select list not in group-by clause error

### LINKED ISSUE #366: Blog Archive Widget Has MySQLcentric Date Logic
The `DATE_FORMAT` function in the section following https://github.com/silverstripe/silverstripe-blog/blob/master/code/widgets/BlogArchiveWidget.php#L93 is MySQL only.

### PR DESCRIPTION
**Pull request by fspringveldt**
Fixes silverstripe/silverstripe-widgets#144
Fixes #366 
Versioning added and mysql-centricity removed as per @kinglozzer

### CODE REVIEW

File: code/widgets/BlogArchiveWidget.php [hunk 1]
```diff
@@ -84,52 +84,45 @@ public function getCMSFields()
...
+        $format = ($this->ArchiveType == 'Yearly') ? '%Y' : '%Y-%m';
+        $publishDate = DB::get_conn()->formattedDatetimeClause('"PublishDate"', $format);
+        $fields = array(
+            'PublishDate' => $publishDate,
+            'Total' => "Count('PublishDate')"
+        );
+
+        $stage = Versioned::current_stage();
+        $suffix = ($stage == 'Stage') ? '' : "_{$stage}";
+        $query = SQLSelect::create($fields, "BlogPost{$suffix}")
```
Comment (kinglozzer) [inline code/widgets/BlogArchiveWidget.php]: As we’re bypassing `BlogPostFilter`, this will need some logic to discard posts with a future publish date

File: code/widgets/BlogArchiveWidget.php [hunk 2]
```diff
@@ -84,52 +84,45 @@ public function getCMSFields()
...
-                }
-
-                $archive->push(new ArrayData(array(
-                    'Title' => $title,
-                    'Link' => Controller::join_links($this->Blog()->Link('archive'), $year, $month)
-                )));
+        $format = ($this->ArchiveType == 'Yearly') ? '%Y' : '%Y-%m';
+        $publishDate = DB::get_conn()->formattedDatetimeClause('"PublishDate"', $format);
+        $fields = array(
+            'PublishDate' => $publishDate,
```
Comment (kinglozzer) [inline code/widgets/BlogArchiveWidget.php]: If we’re going to apply a filter to `PublishDate` (see my comment about discarding future posts), we might need to change the name of the alias for the formatted date clause

Comment (fspringveldt) [inline code/widgets/BlogArchiveWidget.php]: Thanks @kinglozzer. Looks like renaming of the filter wasn't needed after all. Pushing up now.

File: code/widgets/BlogArchiveWidget.php (hunk 1 above)
Comment (fspringveldt) [inline code/widgets/BlogArchiveWidget.php]: Future posts removed.

**Comment by robbieaverill** [comment]
You could remove 6256850 now, it didn't make a difference - the PHP 5.6 build issue in Travis has been "fixed" for now

File: code/widgets/BlogArchiveWidget.php [hunk 3]
```diff
@@ -84,52 +84,47 @@ public function getCMSFields()
     /**
      * Returns a list of months where blog posts are present.
      *
-     * @return DataList
+     * @return ArrayList
```
Comment (robbieaverill) [inline code/widgets/BlogArchiveWidget.php]: Just noting for the record that this is not an API change but an incorrect docblock to start with

File: code/widgets/BlogArchiveWidget.php [hunk 4]
```diff
@@ -84,52 +84,47 @@ public function getCMSFields()
...
+            'PublishDate' => $publishDate,
+            'Total' => "Count('PublishDate')"
+        );
+
+        $stage = Versioned::current_stage();
+        $suffix = ($stage == 'Stage') ? '' : "_{$stage}";
+        $query = SQLSelect::create($fields, "BlogPost{$suffix}")
+            ->addGroupBy($publishDate)
+            ->addOrderBy('PublishDate Desc')
+            ->addWhere(array('PublishDate < ?' => SS_Datetime::now()));
```
Comment (dhensby) [inline code/widgets/BlogArchiveWidget.php]: Does this work correctly? I didn't think passing a `SS_Datetime` object to  a filter/where worked? You may need to add `->Format('Y-m-d')` to the datetime...

**Comment by dhensby** [comment]
bump

**Comment by SpiritLevel** [comment]
I agree with @dhensby: bump! I have two sites in which I have had to remove the archive widget...:)

**Comment by robbieaverill** [comment]
Happy @dhensby?

**Comment by SpiritLevel** [comment]
It would be great to get this merged in :) 

Ping @dhensby

**Comment by derralf** [comment]
little error around lines 109/110
strtotime can't create a valid timestamp when just a year is given (thats what happens when ArchiveType == 'Yearly'). see screenshot.
simple fix in line 112/113 with:
```
if ($this->ArchiveType == 'Yearly') {
                $year = $next['PublishDate'];
                $month = null;
                $title = $year;
} else {
                ...
                ...
```
archivewidget

**Comment by SpiritLevel** [comment]
Yay.

**Comment by dhensby** [comment]
@derralf - it looks like that fix has been taken in?

**Comment by derralf** [comment]
Don't know. I din't fix anything (did not fork, fix, write request or anything).
I just applied my quick hack from above in my local installation (and wanted to tell the developers).
I used this file: https://github.com/creative-commoners/silverstripe-blog/blob/236bf6d8fc86466a953019319202440f071c8133/code/widgets/BlogArchiveWidget.php
 which was merged 7 day ago (just copied the code to my local installation) which made the "group-by clause error" go away but gave me the errors shown in screenshot.
Problem was:
`$date->setValue(strtotime($next['PublishDate']));`
where $next['PublishDate'] is for example "2016" when Yearly is set
but strtotime won't return a correct time with just "2016" given
while strtotime gave a correct time with e.g. "2016-11" (monthly archive)

**Comment by SpiritLevel** [comment]
@dhensby @kinglozzer @robbieaverill Unfortunately, this doesn\t fix https://github.com/silverstripe/silverstripe-blog/issues/453 so reopening.

**Comment by dhensby** [comment]
@derralf hmm - ok, can you please open a new issue regarding this?

**Comment by derralf** [comment]
@dhensby opened a new issue #464
