### PR TITLE
BUG Fix canview for non-admins

### LINKED ISSUE #283: Non-admins using a future PublishDate throws an error in certain cases
When an editor, writer or contributor creates a BlogPost with a future PublishDate the following occurs:
 
1. An error is thrown - [User Notice] Requirements_Backend::combine_files(): Already included files framework/thirdparty/jquery/jquery.js,framework/thirdparty/jquery-ui/jquery-ui.js in combined file 'lib.js'
GET /admin/pages/edit/show/13?locale=en_NZ

Line 1048 in /framework/view/Requirements.php 

 2.  The blog post disappears from the Blog gridfield while I'm logged in as this non-admin user

 3. If I log in as an admin, I can see these future scheduled posts.

Have replicated the issue on fresh checkout of cwp recipe 1.1.0 on both local dev, a uat and a prod environment.

### PR DESCRIPTION
**Pull request by tractorcow**
If a writer creates a page in the future, before this it would instantly crash the CMS.

Fixes #283

### CODE REVIEW

File: tests/BlogPostTest.php [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+	/**
+	 * {@inheritdoc}
+	 */
+	public function tearDown() {
+		SS_Datetime::clear_mock_now();
+		parent::tearDown();
+	}
+
+	
+	public function testCanView() {
```
Comment (assertchris) [inline tests/BlogPostTest.php]: can't you use a data provider for this repetitive mess?

Comment (tractorcow) [inline tests/BlogPostTest.php]: Fixed.

**Comment by tractorcow** [comment]
ta
